### ISSUE TITLE
When calling delay right after an AsyncLog await, I get "Error - 159 - Exception in dynamic procedure call."

### ISSUE THREAD

**Issue by MolaeMaceria** [JanJorgensen/StepBro#14]
Stacktrace:
TargetInvocationException - Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at StepBro.Core.Execution.ExecutionHelperMethods.DynamicProcedureCall(IProcedureReference procedure, IScriptCallContext context, PropertyBlock propertyBlock, Object[] sequencialFirstArguments, ArgumentList namedArguments, Object[] sequencialLastArguments) in C:\SW_development\StepBro\source\StepBro.Core\Execution\ExecutionHelperMethods.cs:line 415

Example testcase:
procedure void mmcSmokeTest() : TestCase
{
    step "ResetMMC";
        MMC.SendDirect("reset"); // Reset the MMC
    step "AwaitLastTraceMessage";
        MMC.AsyncLog.Await("Remote state: Locked (2)", 60s); // Await the last trace that matters after startup
        delay(30s);
}

**Comment by MolaeMaceria** [comment]
Has been fixed.
